# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Cortex_A9/Cortex_A9.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Cortex_A9 || ORIG_REF_NAME==Cortex_A9}]

# IP: bd/Cortex_A9/ip/Cortex_A9_processing_system7_0_0/Cortex_A9_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Cortex_A9_processing_system7_0_0 || ORIG_REF_NAME==Cortex_A9_processing_system7_0_0}]

# IP: bd/Cortex_A9/ip/Cortex_A9_axi_gpio_0_0/Cortex_A9_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Cortex_A9_axi_gpio_0_0 || ORIG_REF_NAME==Cortex_A9_axi_gpio_0_0}]

# IP: bd/Cortex_A9/ip/Cortex_A9_ps7_0_axi_periph_1/Cortex_A9_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Cortex_A9_ps7_0_axi_periph_1 || ORIG_REF_NAME==Cortex_A9_ps7_0_axi_periph_1}]

# IP: bd/Cortex_A9/ip/Cortex_A9_rst_ps7_0_100M_1/Cortex_A9_rst_ps7_0_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Cortex_A9_rst_ps7_0_100M_1 || ORIG_REF_NAME==Cortex_A9_rst_ps7_0_100M_1}]

# IP: bd/Cortex_A9/ip/Cortex_A9_axi_gpio_0_1/Cortex_A9_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Cortex_A9_axi_gpio_0_1 || ORIG_REF_NAME==Cortex_A9_axi_gpio_0_1}]

# IP: bd/Cortex_A9/ip/Cortex_A9_xbar_0/Cortex_A9_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Cortex_A9_xbar_0 || ORIG_REF_NAME==Cortex_A9_xbar_0}]

# IP: bd/Cortex_A9/ip/Cortex_A9_auto_pc_0/Cortex_A9_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Cortex_A9_auto_pc_0 || ORIG_REF_NAME==Cortex_A9_auto_pc_0}]

# XDC: bd/Cortex_A9/Cortex_A9_ooc.xdc
