# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/kmd17/Documents/GitHub/Embedded_Systems_lab2_ARM/2.Interrupts/Part2_Interrupts.srcs/sources_1/bd/Cortex_A9/ip/Cortex_A9_axi_gpio_0_1/Cortex_A9_axi_gpio_0_1.xci
# IP: The module: 'Cortex_A9_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kmd17/Documents/GitHub/Embedded_Systems_lab2_ARM/2.Interrupts/Part2_Interrupts.srcs/sources_1/bd/Cortex_A9/ip/Cortex_A9_axi_gpio_0_1/Cortex_A9_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Cortex_A9_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/kmd17/Documents/GitHub/Embedded_Systems_lab2_ARM/2.Interrupts/Part2_Interrupts.srcs/sources_1/bd/Cortex_A9/ip/Cortex_A9_axi_gpio_0_1/Cortex_A9_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Cortex_A9_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/kmd17/Documents/GitHub/Embedded_Systems_lab2_ARM/2.Interrupts/Part2_Interrupts.srcs/sources_1/bd/Cortex_A9/ip/Cortex_A9_axi_gpio_0_1/Cortex_A9_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'Cortex_A9_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/kmd17/Documents/GitHub/Embedded_Systems_lab2_ARM/2.Interrupts/Part2_Interrupts.srcs/sources_1/bd/Cortex_A9/ip/Cortex_A9_axi_gpio_0_1/Cortex_A9_axi_gpio_0_1.xci
# IP: The module: 'Cortex_A9_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kmd17/Documents/GitHub/Embedded_Systems_lab2_ARM/2.Interrupts/Part2_Interrupts.srcs/sources_1/bd/Cortex_A9/ip/Cortex_A9_axi_gpio_0_1/Cortex_A9_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Cortex_A9_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/kmd17/Documents/GitHub/Embedded_Systems_lab2_ARM/2.Interrupts/Part2_Interrupts.srcs/sources_1/bd/Cortex_A9/ip/Cortex_A9_axi_gpio_0_1/Cortex_A9_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Cortex_A9_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/kmd17/Documents/GitHub/Embedded_Systems_lab2_ARM/2.Interrupts/Part2_Interrupts.srcs/sources_1/bd/Cortex_A9/ip/Cortex_A9_axi_gpio_0_1/Cortex_A9_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'Cortex_A9_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
